const PDFDocument = require('pdfkit');
const {
  drawPdfOrganizationHeader,
  getOrganizationSettings,
  registerPdfBengaliFont,
} = require('./organizationBranding');

const BRAND = {
  primary: '#0f766e',
  dark: '#0f172a',
  muted: '#64748b',
  text: '#1f2937',
  border: '#e2e8f0',
  accent: '#ecfdf5',
};

function money(value) {
  return `$${Number(value || 0).toFixed(2)}`;
}

function formatDate(value) {
  if (!value) return '—';
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return '—';
  return date.toLocaleString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}

function formatShortDate(value) {
  if (!value) return '—';
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return '—';
  return date.toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });
}

function createPdfBuffer(buildFn) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 48, bufferPages: true });
    const buffers = [];
    doc.on('data', (chunk) => buffers.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(buffers)));
    doc.on('error', reject);
    buildFn(doc);
    doc.end();
  });
}

function drawBrandHeader(doc, { title, subtitle, generatedBy }) {
  const pageWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;
  doc.save();
  doc.rect(doc.page.margins.left, doc.page.margins.top - 8, pageWidth, 4).fill(BRAND.primary);
  doc.restore();

  drawPdfOrganizationHeader(doc, { title, subtitle, align: 'left', titleSize: 16, issuerSize: 18 });
  doc.font('Helvetica').fontSize(10).fillColor(BRAND.muted);
  doc.text(`Generated by: ${generatedBy || 'Cashier'}`);
  doc.text(`Generated at: ${formatDate(new Date())}`);
  doc.moveDown(0.8);
}

function drawSummaryCards(doc, cards = []) {
  const startX = doc.page.margins.left;
  const cardWidth = (doc.page.width - doc.page.margins.left - doc.page.margins.right - 16) / Math.min(cards.length, 4);
  const y = doc.y;

  cards.forEach((card, index) => {
    const x = startX + index * (cardWidth + 8);
    doc.save();
    doc.roundedRect(x, y, cardWidth, 52, 6).fillAndStroke(BRAND.accent, BRAND.border);
    doc.fillColor(BRAND.muted).fontSize(9).text(card.label, x + 10, y + 10, { width: cardWidth - 20 });
    doc.fillColor(BRAND.dark).fontSize(13).text(card.value, x + 10, y + 26, { width: cardWidth - 20 });
    doc.restore();
  });

  doc.y = y + 64;
}

function ensureSpace(doc, height = 80) {
  const bottom = doc.page.height - doc.page.margins.bottom;
  if (doc.y + height > bottom) {
    doc.addPage();
  }
}

function drawSectionTitle(doc, title) {
  ensureSpace(doc, 40);
  doc.fontSize(13).fillColor(BRAND.dark).text(title, { underline: true });
  doc.moveDown(0.5);
}

function drawKeyValueTable(doc, rows = []) {
  rows.forEach(([label, value]) => {
    ensureSpace(doc, 18);
    doc.fontSize(10).fillColor(BRAND.muted).text(`${label}:`, { continued: true });
    doc.fillColor(BRAND.text).text(` ${value}`);
  });
  doc.moveDown(0.6);
}

function drawDataTable(doc, { columns, rows, emptyText = 'No records.' }) {
  const tableLeft = doc.page.margins.left;
  const tableWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;
  const colWidth = tableWidth / columns.length;

  const drawHeader = () => {
    ensureSpace(doc, 28);
    const headerY = doc.y;
    doc.save();
    doc.rect(tableLeft, headerY, tableWidth, 20).fill(BRAND.primary);
    columns.forEach((column, index) => {
      doc.fillColor('#ffffff').fontSize(9).text(
        column.label,
        tableLeft + index * colWidth + 6,
        headerY + 6,
        { width: colWidth - 10 }
      );
    });
    doc.restore();
    doc.y = headerY + 24;
  };

  drawHeader();

  if (!rows.length) {
    doc.fontSize(10).fillColor(BRAND.muted).text(emptyText);
    doc.moveDown(0.6);
    return;
  }

  rows.forEach((row, rowIndex) => {
    ensureSpace(doc, 22);
    const rowY = doc.y;
    if (rowIndex % 2 === 0) {
      doc.save();
      doc.rect(tableLeft, rowY - 2, tableWidth, 18).fill('#f8fafc');
      doc.restore();
    }
    columns.forEach((column, index) => {
      const value = typeof column.format === 'function'
        ? column.format(row)
        : String(row[column.key] ?? '—');
      doc.fontSize(8.5).fillColor(BRAND.text).text(
        value,
        tableLeft + index * colWidth + 6,
        rowY,
        { width: colWidth - 10 }
      );
    });
    doc.y = rowY + 18;
  });
  doc.moveDown(0.8);
}

function addPageNumbers(doc) {
  const settings = getOrganizationSettings();
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i += 1) {
    doc.switchToPage(i);
    registerPdfBengaliFont(doc);
    const footerFont = doc._bbbfBengaliFont ? 'NotoSansBengali' : 'Helvetica';
    doc.font(footerFont).fontSize(8).fillColor(BRAND.muted).text(
      `Page ${i - range.start + 1} of ${range.count} · Official ${settings.nameBn} document`,
      doc.page.margins.left,
      doc.page.height - doc.page.margins.bottom + 12,
      { align: 'center', width: doc.page.width - doc.page.margins.left - doc.page.margins.right }
    );
  }
}

async function generateMemberLedgerPdf(data, generatedBy = 'Cashier') {
  return createPdfBuffer((doc) => {
    const settings = getOrganizationSettings();
    const member = data.member || {};
    drawBrandHeader(doc, {
      title: 'Member Financial Statement',
      subtitle: 'Official ledger — deposits, profits, shares, and transaction history',
      generatedBy,
    });

    drawSummaryCards(doc, [
      { label: 'Savings', value: money(member.savings) },
      { label: 'Advance', value: money(data.advanceBalance ?? member.advanceBalance) },
      { label: 'Profit', value: money(member.profit) },
      { label: 'Lifetime deposits', value: money(data.totalDeposits) },
    ]);

    drawSectionTitle(doc, 'Member details');
    drawKeyValueTable(doc, [
      ['Name', member.name || '—'],
      ['Email', member.email || '—'],
      ['Phone', member.phone || '—'],
      ['Status', member.status || 'active'],
      ['Member ID', String(member._id || '—')],
    ]);

    const current = data.currentMonthStatus || {};
    drawSectionTitle(doc, 'Current month contribution');
    drawKeyValueTable(doc, [
      ['Month', current.monthLabel || current.yearMonth || '—'],
      ['Target', current.targetAmount != null ? money(current.targetAmount) : '—'],
      ['Paid', money(current.paidAmount)],
      ['Still due', money(current.unpaidAmount)],
      ['Surplus to advance', money(current.surplusToAdvance)],
      ['Status', current.status || '—'],
    ]);

    drawSectionTitle(doc, 'Contribution history');
    const dues = data.contributionDues || [];
    drawDataTable(doc, {
      columns: [
        { label: 'Month', key: 'yearMonth' },
        { label: 'Expected', format: (row) => (row.expectedAmount != null ? money(row.expectedAmount) : '—') },
        { label: 'Paid', format: (row) => money(row.paidAmount) },
        { label: 'Unpaid', format: (row) => money(row.unpaidAmount) },
        { label: 'Status', key: 'status' },
      ],
      rows: dues,
      emptyText: 'No contribution records.',
    });

    drawSectionTitle(doc, 'Complete transaction ledger');
    drawDataTable(doc, {
      columns: [
        { label: 'Date', format: (row) => formatShortDate(row.date) },
        { label: 'Type', key: 'type' },
        { label: 'Direction', key: 'direction' },
        { label: 'Amount', format: (row) => money(row.amount) },
        { label: 'Month', key: 'month' },
        { label: 'Notes', key: 'notes' },
      ],
      rows: data.transactions || [],
      emptyText: 'No transactions recorded.',
    });

    doc.font('Helvetica').fontSize(9).fillColor(BRAND.muted).text(
      `This is an official financial statement of ${settings.nameBn} (${settings.nameEn}) generated for auditing and record-keeping. Deposit receipts are available individually via the cashier portal.`,
      { align: 'center' }
    );

    addPageNumbers(doc);
  });
}

async function generateInvestorPortfolioPdf(data, generatedBy = 'Cashier') {
  return createPdfBuffer((doc) => {
    const investor = data.investor || {};
    const summary = data.summary || {};

    drawBrandHeader(doc, {
      title: 'Investor Portfolio Statement',
      subtitle: 'Official record of investments, shares, profits, and project participation',
      generatedBy,
    });

    drawSummaryCards(doc, [
      { label: 'Total invested', value: money(summary.totalAmount) },
      { label: 'Active amount', value: money(summary.activeAmount) },
      { label: 'Sold amount', value: money(summary.soldAmount) },
      { label: 'Projects', value: String(summary.totalInvestments || 0) },
    ]);

    drawSectionTitle(doc, 'Investor details');
    drawKeyValueTable(doc, [
      ['Name', investor.name || '—'],
      ['Email', investor.email || '—'],
      ['Phone', investor.phone || '—'],
      ['Status', investor.status || 'active'],
      ['Investor ID', String(investor._id || '—')],
    ]);

    drawSectionTitle(doc, 'Investments by type');
    drawDataTable(doc, {
      columns: [
        { label: 'Type', key: 'investmentType' },
        { label: 'Count', key: 'count' },
        { label: 'Total', format: (row) => money(row.totalAmount) },
        { label: 'Active', format: (row) => money(row.activeAmount) },
        { label: 'Sold', format: (row) => money(row.soldAmount) },
      ],
      rows: data.byType || [],
      emptyText: 'No investments by type.',
    });

    drawSectionTitle(doc, 'Investment transaction history');
    drawDataTable(doc, {
      columns: [
        { label: 'Date', format: (row) => formatShortDate(row.date) },
        { label: 'Code', key: 'code' },
        { label: 'Type', key: 'type' },
        { label: 'Status', key: 'status' },
        { label: 'Amount', format: (row) => money(row.amount) },
        { label: 'Profit', format: (row) => money(row.profit) },
        { label: 'Net', format: (row) => money(row.netBalance) },
      ],
      rows: data.transactions || [],
      emptyText: 'No investments recorded.',
    });

    doc.fontSize(9).fillColor(BRAND.muted).text(
      'This portfolio statement reflects all society investments linked to the investor at the time of generation.',
      { align: 'center' }
    );

    addPageNumbers(doc);
  });
}

async function generateAuditTrailPdf(auditData, generatedBy = 'Cashier') {
  return createPdfBuffer((doc) => {
    const { filters = {}, summary = {}, ledger = {}, transactions = [] } = auditData;
    const filterParts = [
      filters.from ? `From ${filters.from}` : null,
      filters.to ? `To ${filters.to}` : null,
      filters.category && filters.category !== 'all' ? `Category: ${filters.category}` : 'All categories',
    ].filter(Boolean);

    drawBrandHeader(doc, {
      title: 'Society Transaction Audit Report',
      subtitle: filterParts.join(' · ') || 'Complete society-wide money flow audit',
      generatedBy,
    });

    drawSummaryCards(doc, [
      { label: 'Total in', value: money(summary.totalIn) },
      { label: 'Total out', value: money(summary.totalOut) },
      { label: 'Net flow', value: money(summary.net) },
      { label: 'Transactions', value: String(summary.count || 0) },
    ]);

    drawSectionTitle(doc, 'Bank ledger position');
    drawKeyValueTable(doc, [
      ['Book balance', money(ledger.bookBalance)],
      ['Opening balance', ledger.openingBalance != null ? money(ledger.openingBalance) : '—'],
      ['Last actual balance', ledger.actualBalance != null ? money(ledger.actualBalance) : '—'],
      ['Reconciliation difference', ledger.difference != null ? money(ledger.difference) : '—'],
    ]);

    if ((summary.byCategory || []).length) {
      drawSectionTitle(doc, 'Breakdown by category');
      drawDataTable(doc, {
        columns: [
          { label: 'Category', key: 'label' },
          { label: 'Count', key: 'count' },
          { label: 'In', format: (row) => money(row.totalIn) },
          { label: 'Out', format: (row) => money(row.totalOut) },
        ],
        rows: summary.byCategory,
      });
    }

    drawSectionTitle(doc, 'Transaction audit trail');
    drawDataTable(doc, {
      columns: [
        { label: 'Date', format: (row) => formatDate(row.occurredAt) },
        { label: 'Category', key: 'categoryLabel' },
        { label: 'Direction', key: 'direction' },
        { label: 'Amount', format: (row) => money(row.amount) },
        { label: 'Description', key: 'description' },
        { label: 'Actor', key: 'actor' },
      ],
      rows: transactions,
      emptyText: 'No transactions matched the selected filters.',
    });

    doc.fontSize(9).fillColor(BRAND.muted).text(
      'This audit report consolidates bank ledger movements, processed withdrawals, and completed refunds for official record-keeping.',
      { align: 'center' }
    );

    addPageNumbers(doc);
  });
}

module.exports = {
  generateMemberLedgerPdf,
  generateInvestorPortfolioPdf,
  generateAuditTrailPdf,
};
