function resolveRequestLanguage(req, fallback = 'bn') {
  const raw = String(req?.query?.lang || req?.session?.user?.preferredLanguage || fallback).toLowerCase();
  return raw === 'en' ? 'en' : 'bn';
}

const PDF_STRINGS = {
  en: {
    memberStatement: 'Member Financial Statement',
    memberStatementSubtitle: 'Official ledger — deposits, profits, shares, and transaction history',
    investorStatement: 'Investor Portfolio Statement',
    investorStatementSubtitle: 'Official record of investments, shares, profits, and project participation',
    auditTrail: 'Transaction Audit Trail',
    auditTrailSubtitle: 'Society-wide financial movements and ledger reconciliation',
    generatedBy: 'Generated by',
    generatedAt: 'Generated at',
    officialFooter: 'Official financial document',
    depositReceipt: 'Official Receipt',
    depositReceiptSubtitle: 'Digital money receipt / invoice',
    pageOf: 'Page',
    of: 'of',
    officialDocument: 'Official document',
  },
  bn: {
    memberStatement: 'সদস্য আর্থিক বিবরণী',
    memberStatementSubtitle: 'অফিসিয়াল লেজার — জমা, লাভ, শেয়ার ও লেনদেনের ইতিহাস',
    investorStatement: 'বিনিয়োগকারী পোর্টফোলিও বিবরণী',
    investorStatementSubtitle: 'বিনিয়োগ, শেয়ার, লাভ ও প্রকল্প অংশগ্রহণের অফিসিয়াল রেকর্ড',
    auditTrail: 'লেনদেন নিরীক্ষা ট্রেইল',
    auditTrailSubtitle: 'সমগ্র সমিতির আর্থিক চলাচল ও লেজার সমন্বয়',
    generatedBy: 'তৈরি করেছেন',
    generatedAt: 'তৈরির সময়',
    officialFooter: 'অফিসিয়াল আর্থিক নথি',
    depositReceipt: 'অফিসিয়াল রসিদ',
    depositReceiptSubtitle: 'ডিজিটাল মানি রসিদ / ইনভয়েস',
    pageOf: 'পৃষ্ঠা',
    of: 'এর',
    officialDocument: 'অফিসিয়াল নথি',
  },
};

function pdfText(lang, key) {
  const normalized = lang === 'en' ? 'en' : 'bn';
  return PDF_STRINGS[normalized][key] || PDF_STRINGS.en[key] || key;
}

module.exports = {
  resolveRequestLanguage,
  pdfText,
};
